apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app.kubernetes.io/name: service2
spec:
  selector:
    app.kubernetes.io/name: service2
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
