apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/service1
  - ../../base/service2
  - ingress.yaml
images:
  - name: harbor.example.com/library/service1
    newTag: main-latest
  - name: harbor.example.com/library/service2
    newTag: main-latest
replicas:
  - name: service1
    count: 2
  - name: service2
    count: 2
patches:
  - path: service1-resources.yaml
  - path: service2-resources.yaml
