apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
  labels:
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/x412703/pipes.git
    targetRevision: HEAD
    path: project/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
