apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base/service1
  - ../../base/service2
  - ingress.yaml
images:
  - name: harbor.example.com/library/service1
    newTag: dev-latest
  - name: harbor.example.com/library/service2
    newTag: dev-latest

namePrefix: dev-